[tool.black]
line-length = 80
skip-magic-trailing-comma = true
target-version = ["py310"]

[tool.pytest.ini_options]
addopts = ["-rsxX", "--color=auto", "--strict-markers"]
filterwarnings = ["error", "ignore::DeprecationWarning"]
minversion = "7.0"
python_files = ["tests.py", "test_*.py"]
testpaths = "app"
xfail_strict = true
looponfailroots = "src"
DJANGO_SETTINGS_MODULE = "app.settings"

[tool.pyright]
include = ["app"]
exclude = ["**/migrations/**", "**/tests.py"]
venvPath = ".direnv"
pythonVersion = "3.10"
pythonPlatform = "Linux"
executionEnvironments = [{ root = "app" }]
typeCheckingMode = "strict"
reportMissingTypeStubs = false
reportUnknownArgumentType = false
reportUnknownMemberType = false
reportUnknownVariableType = false
reportUntypedBaseClass = false
