# Generated by Django 4.0.4 on 2022-04-17 09:31
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("movie", "0002_review")]

    operations = [
        migrations.RenameField(
            model_name="review", old_name="watchAgain", new_name="watch_again"
        )
    ]
